# Site settings
title: Ryan Arnaudin
myname: Ryan Arnaudin
email: arnaudin@ryanarnaudin.com
timezone: America/Los_Angeles
description: > # this means to ignore newlines until "baseurl:"
  Ryan Arnaudin is a designer & engineer in San Francisco, CA
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ryanarnaudin.com/" # the base hostname & protocol for your site
name: Ryan Arnaudin
twitter_username: arnaudin
github_username:  arnaudin
gplus_username: RyanArnaudin
instagram_username: arnaudin
linkedin_username: arnaudin
codepen_username: arnaudin
medium_username: arnaudin
amazon_associate_id: ryanarna-20
highlighter: pygments
encoding: utf-8
permalink: pretty

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: default    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]
future: true

more_vert:
  option1:
    name: Cool Option 1
    link: www.myawesomelink.com
  option2:
    name: Cool Option 2
    link: www.myawesomelink.com
  option3:
    name: Cool Option 3
    link: www.myawesomelink.com

# Build settings
markdown: kramdown
